### ISSUE TITLE
Tag Error

### ISSUE THREAD

**Issue by Siva-93** [szrnka-peter/ngAdsense#6]
Hi, 

I have used this plugin to show the Ads in my angular application. But still I can't get through it. It shows the error like

TagError: adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them.
    at kf (http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:71:329)
    at c.client (http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:68:208)
    at http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:17:478
    at qc (http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:17:70)
    at oc.<anonymous> (http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:17:448)
    at http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:17:1094
    at yc (http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:17:807)
    at http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:17:1067
    at Fc (http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:21:120)
    at Object.df [as push] (http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js:68:187) <div class="main-view ng-scope" ui-view="">

Could you help me to get out of from this?

Thanks

**Comment by peter-szrnka** [comment]
Hi,

Which version of Angular JS runs in your application?

**Comment by DigitalMystery** [comment]
Same here.... 1.5.8 @szrnka-peter 
@Siva-93 did you ever figure out the issue?

**Comment by DigitalMystery** [comment]
Ok, I changed from using the min file to the regular file and that fixed the issue.  However, I just have a blank space for the ad now.  If one of you guys knows why that is that would be great!

**Comment by peter-szrnka** [comment]
Sorry for the late answer. Now I've tested with v1.6.4, and I didn't see any problem.

**Comment by peter-szrnka** [comment]
Fixed in v1.4
